version: 2
jobs:

  build:
    docker:
      - image: circleci/java
      - image: redis
    steps:
      - checkout
      - run: cp gradle.properties.example gradle.properties
      - run: ./gradlew dependencies
      - run: ./gradlew test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/;
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - persist_to_workspace:
          root: build
          paths:
            - classes

  packaging:
    docker:
      - image: circleci/java
    steps:
      - run: sudo apt-get install make -y -q
      - checkout
      - attach_workspace:
          at: build
      - run: cat gradle.properties.example >>gradle.properties
      - run:
          name: build all SDK jars
          command: ./gradlew publishToMavenLocal -P LD_SKIP_SIGNING=1
      - run:
          name: run packaging tests
          command: cd packaging-test && make all

workflows:
  version: 2
  test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - packaging:
          requires:
            - build
          filters:
            branches:
              ignore:
                - gh-pages
